### ISSUE TITLE
abandoned?

### ISSUE THREAD

**Issue by pwright** [isomorphic-git/cli#3]
I came here, because I couldn't find the cli mentioned in main docs.

I tried ```npm install -g @isomorphic-git/cli``` but got a 'not found' error and wonder if it's still a 'thing'?

**Comment by danguilherme** [comment]
Apparently it was moved to the main repository: https://github.com/isomorphic-git/isomorphic-git/tree/v0.78.0#isogit-cli.

**Comment by pwright** [comment]
gotcha, thanks
